name: 🚀 Deploy to Self-Hosted Ubuntu | VPS Sieu Toc

on:
  push:
    branches:
      - main
env:
  NGINX_SERVER_NAME: "justdemo.work"

jobs:
  # build on Github Ubuntu to save the resource
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend
        run: |
          cd frontend
          npm i --legacy-peer-deps
          npm run build
          # Replace placeholder with actual server name
          sed -i "s/\${NGINX_SERVER_NAME}/${{ env.NGINX_SERVER_NAME }}/g" nginx.conf
          cp nginx.conf dist/

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proplan-hub-dist
          path: dist

  deploy-frontend:
    runs-on: [self-hosted, home, dellbuntu]
    needs: build-frontend
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: proplan-hub-dist
          path: dist

      - name: Prepare nginx deploy path
        run: |
          sudo mkdir -p /var/www/proplan-hub
          sudo chown -R cicd:cicd /var/www/proplan-hub

      - name: Deploy frontend to nginx folder
        run: |
          sudo rm -rf /var/www/proplan-hub/dist
          sudo cp -r dist /var/www/proplan-hub/dist
          sudo cp -r dist/nginx.conf /etc/nginx/sites-available/proplan-hub
          sudo ln -sf /etc/nginx/sites-available/proplan-hub /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx
